version: "3.9"
services:
    turbinesvc:
        container_name: "turbine-svc"
        build: ./TurbineSvc
        ports:
            - "5001:5000"
        depends_on:
            - db
        links:
            - db
        restart: 'always'
        environment:
            SVC_PORT: "5000"
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_WEB_USER}"
            DB_PASSWORD: "${DB_WEB_PASSWORD}"
            DB_SERVER: db
            DB_PORT: "3306"
            #DB_SSL_CERT: "DigiCertGlobalRootG2.crt.pem"

    measurmentfnc:
        container_name: "measurement-fnc"
        build: ./MeasurementFnc
        ports:
            - "7072:80"
        depends_on:
            - db
        links:
            - db
        restart: 'always'
        environment:
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_FUNC_USER}"
            DB_PASSWORD: "${DB_FUNC_PASSWORD}"
            DB_SERVER: db
            DB_PORT: "3306"
            #DB_SSL_CERT: "DigiCertGlobalRootG2.crt.pem"
            
    db:
        container_name: "turbine-db"
        image: "mariadb:10"
        restart: 'always'
        ports:
            - "3308:3306"
        environment:
            MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        volumes:
            #- ./conf.d:/etc/mysql/conf.d/:ro
            - ./db:/docker-entrypoint-initdb.d/:ro
