version: "3.9"
services:
    turbinesvc:
        container_name: "turbine-svc"
        build: ./TurbineSvc
        ports:
            - "5001:5000"
        depends_on:
            - db
        links:
            - db
        restart: 'always'
        environment:
            SVC_PORT: "5000"
            DB_DRIVER: "mariadb+mariadbconnector"
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_USER}"
            DB_PASSWORD: "${DB_PASSWORD}"
            DB_SERVER: db
            DB_PORT: "3306"
            
    db:
        container_name: "turbine-db"
        image: "mariadb:10"
        restart: 'always'
        ports:
            - "3308:3306"
        environment:
            MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro


