version: "3.9"
services:
    turbineSvc:
        container_name: "turbine_svc"
        build: .
        ports:
            - "8888:8888"
        depends_on:
            - db
        links:
            - db
        restart: 'always'
        environment:
            SVC_HOST: "${SVC_HOST}"
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_USER}"
            DB_SERVER: db
        secrets: 
            - db_password
      measurementFunc:
        container_name: "measurement_func"
        build: .
        ports:
            - "9999:9999"
        depends_on:
            - db
        links:
            - db
        restart: 'always'
        environment:
            SVC_HOST: "${SVC_HOST}"
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_USER}"
            DB_SERVER: db
        secrets: 
            - db_password
    db:
        container_name: "maria_db"
        image: "mariadb:10"
        ports:
            - "3306:3306"
        environment:
            DB_USER: "${DB_PASSWORD}"
            DB_NAME: "${DB_NAME}"
        secrets: 
            - db_root_password
            - db_password
        volumes:
            - ./docker-entrypoint-initdb.d

secrets:
    db_root_password:
        file: db_root_password.txt
    db_password:
        file: db_password.txt